version: '3.8'

services:
  horoscopo-pokemon:
    build: .
    ports:
      - "8080:80"
    container_name: horoscopo-pokemon-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production 